// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commentrequest.proto

package protobufs;

public interface CommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobufs.CommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string author = 1;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>optional string author = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>optional string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional string postId = 3;</code>
   */
  java.lang.String getPostId();
  /**
   * <code>optional string postId = 3;</code>
   */
  com.google.protobuf.ByteString
      getPostIdBytes();
}
